"""
Identifies normative challenges to AI use in PR discussions: comments
that question, regulate, criticize, or restrict AI use as a practice
(rather than just critique a single AI output).

These are CSCW-relevant because they surface community norm formation
around AI participation, which is invisible in pure invocation/uptake
counts.

Patterns matched (case-insensitive):
  - "ai slop", "ai-generated slop", "llm slop", "vibe coding"
  - "please (do )?n[o']?t use" + ai|copilot|chatgpt|claude|llm
  - "stop using" + ai|copilot|chatgpt
  - "don't use" + ai|copilot|chatgpt|llm
  - "no (more )?(ai|copilot|chatgpt)"
  - "ai-generated" / "generated by ai" + negative cue (low quality, slop, etc.)
  - "this is (clearly|obviously|just) (ai|copilot|chatgpt|generated)"
  - "human (review|written)" framing AI as opposite
  - "low(-| )effort" near ai/copilot/chatgpt/llm
  - "looks like ai" / "reads like ai"
  - bans, policies: "we (don't|do not) (allow|permit|use)" + ai
  - mentions of internal policy: "policy", "guideline", "rule" + ai

Output:
  analysis_ai_refs/norm_violations_hits.csv
  analysis_ai_refs/norm_violations_summary.md
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

import pandas as pd

PATTERNS = [
    ("ai_slop", r"\b(ai|llm|gpt|copilot|chatgpt|claude)[- ]?slop\b"),
    ("vibe_coding", r"\bvibe[- ]?cod\w*\b"),
    (
        "explicit_ban",
        r"(please\s+(?:do\s+)?n['o]?t\s+use|don['']?t\s+use|stop\s+using|"
        r"do\s+not\s+use|we\s+(?:don['']?t|do\s+not)\s+(?:allow|permit|use)|"
        r"no\s+(?:more\s+)?)\s*"
        r"(ai|copilot|chatgpt|claude|llm|gpt|gemini|cursor)\b",
    ),
    (
        "low_quality_attribution",
        r"\b(this|it)\s+(is|reads|looks|sounds|feels)\s+(?:clearly\s+|obviously\s+|just\s+)?"
        r"(?:like\s+)?(ai|llm|gpt|copilot|chatgpt|claude)[- ]?(generated|written|output)?\b",
    ),
    (
        "low_effort",
        r"\b(low[- ]?effort|lazy|spam(?:my)?)\b.{0,40}\b"
        r"(ai|copilot|chatgpt|claude|llm|gpt)\b",
    ),
    (
        "ai_inverse",
        r"\b(ai|copilot|chatgpt|claude|llm|gpt)\b.{0,40}\b"
        r"(low[- ]?effort|lazy|spam(?:my)?|nonsense|hallucinat\w+|garbage|junk)\b",
    ),
    (
        "human_review_framing",
        r"\b(human|manual)\s+(review|written|verified|check|audit)\b.{0,80}\b"
        r"(ai|copilot|chatgpt|claude|llm|gpt|generated)\b",
    ),
    (
        "policy_or_guideline",
        r"\b(policy|guideline|rule|forbidden|prohibited|disallow\w*)\b.{0,80}\b"
        r"(ai|copilot|chatgpt|claude|llm|gpt|generated)\b",
    ),
    (
        "ai_inverse_human",
        r"\b(ai|copilot|chatgpt|claude|llm|gpt)\b.{0,80}\b"
        r"(human|manual)\s+(review|written|verified|check|audit)\b",
    ),
    (
        "ai_disclosure_required",
        r"\b(disclose|disclosure|attribute|attribution|flag|label|mark)\b.{0,80}\b"
        r"(ai|copilot|chatgpt|claude|llm|gpt|generated)\b",
    ),
    (
        "did_you_use_ai",
        r"\b(did|are)\s+you\s+(?:just\s+)?(?:using|use|using|generate(?:d)?)\b"
        r".{0,40}\b(ai|copilot|chatgpt|claude|llm|gpt)\b",
    ),
    (
        "trust_marker",
        r"\b(don['']?t|do\s+not|cannot|can\s*not)\s+trust\b.{0,40}\b"
        r"(ai|copilot|chatgpt|claude|llm|gpt)\b",
    ),
    (
        "verify_before_merge",
        r"\b(verify|double[- ]?check|re[- ]?review)\b.{0,40}\b"
        r"(ai|copilot|chatgpt|claude|llm|gpt|generated)\b",
    ),
]

COMPILED = [(name, re.compile(pat, re.IGNORECASE | re.DOTALL)) for name, pat in PATTERNS]


def find_hits(body: str) -> list[tuple[str, str]]:
    if not isinstance(body, str):
        return []
    hits: list[tuple[str, str]] = []
    for name, pat in COMPILED:
        for m in pat.finditer(body):
            hits.append((name, m.group(0).strip()))
    return hits


def is_bot(login: str) -> bool:
    if not isinstance(login, str):
        return False
    s = login.lower()
    return s.endswith("[bot]") or s.endswith("-bot") or s.endswith("bot")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--comments-csv", default="data_ai_refs/comments.csv")
    parser.add_argument("--reviews-csv", default="data_ai_refs/reviews.csv")
    parser.add_argument(
        "--out-csv",
        default="analysis_ai_refs/norm_violations_hits.csv",
    )
    parser.add_argument(
        "--out-md",
        default="analysis_ai_refs/norm_violations_summary.md",
    )
    parser.add_argument("--n-examples-per-pattern", type=int, default=8)
    args = parser.parse_args()

    rows: list[dict] = []
    for path, source in (
        (args.comments_csv, "comment"),
        (args.reviews_csv, "review"),
    ):
        if not Path(path).exists():
            continue
        df = pd.read_csv(path)
        body_col = "body" if "body" in df.columns else (
            "review_body" if "review_body" in df.columns else None
        )
        if body_col is None:
            continue
        for _, r in df.iterrows():
            hits = find_hits(r.get(body_col, ""))
            if not hits:
                continue
            for pat_name, snippet in hits:
                rows.append(
                    {
                        "source": source,
                        "repo_name": r.get("repo_name", ""),
                        "pr_number": r.get("pr_number", ""),
                        "user_login": r.get("user_login", ""),
                        "is_bot": is_bot(r.get("user_login", "")),
                        "created_at": r.get("created_at", ""),
                        "pattern": pat_name,
                        "snippet": snippet[:280],
                        "body": str(r.get(body_col, ""))[:1200],
                    }
                )

    hits_df = pd.DataFrame(rows)
    hits_df.to_csv(args.out_csv, index=False)

    md: list[str] = []
    md.append("# Normative Challenges to AI Use in PR Discussions\n")
    md.append(
        "This pass searches the AI-reference comment and review corpus for "
        "utterances that *regulate* AI use as a practice rather than merely "
        "respond to a single AI output. The goal is to surface community "
        "norm formation around AI participation: bans, attribution demands, "
        "trust markers, low-effort attributions, and verification "
        "requirements.\n"
    )
    md.append(f"## Total hits: {len(hits_df)}")
    if hits_df.empty:
        md.append("\nNo hits found. Either the patterns are too restrictive "
                  "or community-level normative discourse is rare in this "
                  "corpus.\n")
        Path(args.out_md).write_text("\n".join(md) + "\n")
        print(f"Wrote: {args.out_csv}")
        print(f"Wrote: {args.out_md}")
        return

    md.append(
        f"- Distinct PRs with hits: "
        f"{hits_df.assign(pr_id=hits_df['repo_name'] + '#' + hits_df['pr_number'].astype(str))['pr_id'].nunique()}"
    )
    md.append(f"- Hits authored by bot accounts: {int(hits_df['is_bot'].sum())}")
    md.append(
        f"- Hits authored by humans: "
        f"{int((~hits_df['is_bot']).sum())}\n"
    )
    pat_counts = hits_df["pattern"].value_counts()
    md.append("## Hits by pattern\n")
    for pat, c in pat_counts.items():
        md.append(f"- `{pat}`: {c}")
    md.append("")

    md.append("## Examples per pattern (human-authored only)\n")
    human_hits = hits_df[~hits_df["is_bot"]].copy()
    for pat in pat_counts.index:
        sub = human_hits[human_hits["pattern"] == pat].head(
            args.n_examples_per_pattern
        )
        if sub.empty:
            continue
        md.append(f"### `{pat}` ({len(sub)} shown)\n")
        for _, r in sub.iterrows():
            body_snip = r["body"].replace("\n", " ").replace("\r", " ")[:280]
            md.append(
                f"- **{r['repo_name']}#{r['pr_number']}** "
                f"by `{r['user_login']}` ({r['source']}, {r['created_at']}) "
                f"matched `{r['snippet']}`"
            )
            md.append(f"  > {body_snip}")
        md.append("")

    md.append("## Interpretation hooks\n")
    md.append(
        "- The patterns matched here capture *first-order* normative talk: "
        "explicit bans, attribution demands, trust markers, low-effort "
        "attributions, and verification requirements. These are the kinds "
        "of utterances that signal a community is actively negotiating how "
        "AI fits into its work, rather than treating AI use as an "
        "individual decision."
    )
    md.append(
        "- For CSCW framing, the relevant question is not the absolute "
        "count of hits but whether the hits cluster: a single repository "
        "rolling out an `attribute AI use` rule is qualitatively more "
        "important than the same number of hits scattered across 50 "
        "repositories. Look at the per-PR and per-repo distribution."
    )
    md.append(
        "- For the writeup, even 5-10 well-chosen examples of these "
        "utterances would substantially enrich the descriptive section: "
        "they show what the data looks like beyond the invocation/uptake "
        "frame."
    )

    Path(args.out_md).write_text("\n".join(md) + "\n")
    print(f"Wrote: {args.out_csv}")
    print(f"Wrote: {args.out_md}")
    print(f"Total hits: {len(hits_df)}")
    print(pat_counts.to_dict())


if __name__ == "__main__":
    main()
