#!/usr/bin/env python3
"""
Build a coding-ready sample of AI-reference mentions for qualitative / mixed-method analysis.

Outputs:
- ai_function_coding_sample.csv
- ai_function_codebook.md

Usage example:
python build_ai_function_coding_sample.py \
  --input-dir data_ai_refs \
  --output-dir analysis_ai_refs \
  --sample-size 400
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from analyze_ai_reference_patterns import assign_roles, assign_timing, build_ai_mentions, load_data


FUNCTION_LABELS = [
    "Justification",
    "Explanation",
    "Suggestion",
    "Critique",
    "Meta discussion",
    "Other",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-dir", default="data_ai_refs")
    parser.add_argument("--output-dir", default="analysis_ai_refs")
    parser.add_argument("--sample-size", type=int, default=400)
    return parser.parse_args()


def normalize_text(value: object) -> str:
    if pd.isna(value):
        return ""
    text = str(value).replace("\r\n", "\n").replace("\r", "\n")
    return text.strip()


def heuristic_label(text: str) -> str:
    lower = text.lower()
    if any(term in lower for term in ["shouldn't rely on ai", "should not rely on ai", "we shouldn't rely on ai", "policy", "not rely on ai"]):
        return "Meta discussion"
    if any(term in lower for term in ["looks like ai", "may be wrong", "wrong", "hallucinat", "ai code", "generated code", "bad suggestion"]):
        return "Critique"
    if any(term in lower for term in ["maybe try", "use chatgpt", "use claude", "use copilot", "ask gpt", "suggest using", "@copilot", "@claude"]):
        return "Suggestion"
    if any(term in lower for term in ["generated by", "generated with", "chatgpt suggested", "copilot suggested", "claude suggested", "source", "drafted by"]):
        return "Explanation"
    if any(term in lower for term in ["because chatgpt", "because claude", "because copilot", "ai suggested", "llm suggested", "used chatgpt", "used claude", "used copilot"]):
        return "Justification"
    return "Other"


def bot_flag(user_login: object) -> bool:
    if pd.isna(user_login):
        return False
    login = str(user_login).lower()
    return "[bot]" in login or login.endswith("bot") or login in {"copilot", "coderabbitai", "codecov-io"}


def main() -> None:
    args = parse_args()
    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    pr_df, comments_df, reviews_df = load_data(input_dir)
    mentions = build_ai_mentions(pr_df, comments_df, reviews_df)
    mentions = assign_roles(mentions, comments_df, reviews_df)
    mentions = assign_timing(mentions)
    mentions = mentions.copy()
    mentions["mention_body"] = mentions["mention_body"].map(normalize_text)
    mentions["is_bot_like"] = mentions["user_login"].map(bot_flag)
    mentions["heuristic_function_label"] = mentions["mention_body"].map(heuristic_label)
    mentions["text_length"] = mentions["mention_body"].str.len()

    # Stratified sample across location, role, and bot/non-bot for coding diversity.
    strata_cols = ["mention_location", "speaker_role", "is_bot_like"]
    per_group = max(1, args.sample_size // max(1, mentions.groupby(strata_cols).ngroups))
    sampled = (
        mentions.groupby(strata_cols, group_keys=False)
        .apply(lambda df: df.sample(n=min(len(df), per_group), random_state=42))
        .reset_index(drop=True)
    )

    if len(sampled) < min(args.sample_size, len(mentions)):
        remaining = mentions.loc[~mentions.index.isin(sampled.index)].sample(
            n=min(args.sample_size - len(sampled), len(mentions) - len(sampled)),
            random_state=42,
        )
        sampled = pd.concat([sampled, remaining], ignore_index=True)

    sampled = sampled.drop_duplicates(subset=["repo_name", "pr_number", "mention_id"]).head(args.sample_size).copy()
    sampled["manual_function_label"] = ""
    sampled["manual_secondary_label"] = ""
    sampled["manual_notes"] = ""

    coding_cols = [
        "repo_name",
        "pr_number",
        "mention_id",
        "user_login",
        "is_bot_like",
        "speaker_role",
        "mention_location",
        "mention_time",
        "timing_phase",
        "mention_order_label",
        "heuristic_function_label",
        "manual_function_label",
        "manual_secondary_label",
        "manual_notes",
        "mention_body",
    ]
    sampled[coding_cols].to_csv(output_dir / "ai_function_coding_sample.csv", index=False)

    codebook_lines = [
        "# AI Function Coding Codebook",
        "",
        "Primary labels:",
    ]
    for label in FUNCTION_LABELS:
        codebook_lines.append(f"- {label}")
    codebook_lines.extend(
        [
            "",
            "Definitions:",
            "- Justification: Uses AI mention to defend, justify, or legitimize a code or design choice.",
            "- Explanation: Uses AI mention to disclose provenance, explain where content came from, or document process.",
            "- Suggestion: Recommends using an AI tool or addresses an AI agent with a task/request.",
            "- Critique: Challenges the quality, correctness, or appropriateness of AI-generated output.",
            "- Meta discussion: Talks about policy, norms, trust, or philosophy of AI use in the team/project.",
            "- Other: AI mention is present but does not clearly fit the above labels.",
            "",
            "Recommended coding rules:",
            "- Code the function of the mention in context, not just the keyword itself.",
            "- If multiple functions appear, put the dominant one in `manual_function_label` and the second in `manual_secondary_label`.",
            "- Use `manual_notes` for ambiguity, sarcasm, or cases where bot-generated content complicates interpretation.",
        ]
    )
    (output_dir / "ai_function_codebook.md").write_text("\n".join(codebook_lines), encoding="utf-8")

    print(f"Saved {len(sampled)} coding rows to {output_dir / 'ai_function_coding_sample.csv'}")


if __name__ == "__main__":
    main()
