#!/usr/bin/env python3
"""
Collect GitHub PRs that explicitly reference AI tools (ChatGPT, Copilot, Claude, etc.)
using BigQuery (GH Archive), then enrich them with GitHub REST API metadata and
save summary statistics.

Usage example:
python collect_ai_reference_github.py \
  --start 2025-01-01 \
  --end 2025-12-31 \
  --limit-comments 2000 \
  --output-dir data_ai_refs
"""

from __future__ import annotations

import argparse
import collections
import json
import os
import re
import sys
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import pandas as pd
import requests
from dateutil import parser as dtparser
from google.cloud import bigquery
from tqdm import tqdm


AI_KEYWORDS = [
    "chatgpt",
    "copilot",
    "gpt",
    "claude",
    "llm",
    "generated by ai",
    "generated with ai",
    "assistant suggested",
]

AI_REGEX = re.compile(
    r"\b(chatgpt|copilot|gpt[- ]?4|gpt[- ]?3|gpt|claude|llm|generated by ai|generated with ai)\b",
    re.IGNORECASE,
)


@dataclass
class CandidateComment:
    repo_name: str
    pr_number: int
    comment_id: Optional[str]
    actor_login: Optional[str]
    created_at: str
    comment_body: str
    matched_keyword: Optional[str]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--start", required=True, help="Start date YYYY-MM-DD")
    parser.add_argument("--end", required=True, help="End date YYYY-MM-DD")
    parser.add_argument(
        "--limit-comments",
        type=int,
        default=1000,
        help="Max number of AI-reference comments to pull from BigQuery",
    )
    parser.add_argument(
        "--max-prs",
        type=int,
        default=500,
        help="Max unique PRs to enrich via GitHub API",
    )
    parser.add_argument(
        "--output-dir",
        default="data_ai_refs",
        help="Directory to save CSV/JSON outputs",
    )
    parser.add_argument(
        "--min-stars",
        type=int,
        default=0,
        help="Only keep repos with at least this many stars (GitHub API stage)",
    )
    parser.add_argument(
        "--sleep",
        type=float,
        default=0.2,
        help="Sleep between GitHub API calls",
    )
    return parser.parse_args()


def ensure_env() -> Tuple[str, str]:
    github_token = os.environ.get("GITHUB_TOKEN")
    gcp_project = os.environ.get("GOOGLE_CLOUD_PROJECT")
    if not github_token:
        raise RuntimeError("GITHUB_TOKEN environment variable is required.")
    if not gcp_project:
        raise RuntimeError("GOOGLE_CLOUD_PROJECT environment variable is required.")
    return github_token, gcp_project


def get_bigquery_client(project_id: str) -> bigquery.Client:
    return bigquery.Client(project=project_id)


def build_bq_query() -> str:
    """
    GH Archive note:
    - public dataset: githubarchive
    - payload is JSON string
    - month tables are like githubarchive.month.202501
    """
    return """
    DECLARE start_date DATE DEFAULT @start_date;
    DECLARE end_date DATE DEFAULT @end_date;

    WITH comment_events AS (
      SELECT
        repo.name AS repo_name,
        CAST(JSON_VALUE(payload, '$.issue.number') AS INT64) AS issue_number,
        JSON_VALUE(payload, '$.comment.id') AS comment_id,
        actor.login AS actor_login,
        created_at,
        JSON_VALUE(payload, '$.comment.body') AS comment_body,
        JSON_VALUE(payload, '$.issue.pull_request.url') AS pr_url
      FROM `githubarchive.month.*`
      WHERE _TABLE_SUFFIX BETWEEN FORMAT_DATE('%Y%m', start_date)
                              AND FORMAT_DATE('%Y%m', end_date)
        AND type = 'IssueCommentEvent'
    )
    SELECT
      repo_name,
      issue_number AS pr_number,
      comment_id,
      actor_login,
      CAST(created_at AS STRING) AS created_at,
      comment_body
    FROM comment_events
    WHERE pr_url IS NOT NULL
      AND DATE(created_at) BETWEEN start_date AND end_date
      AND comment_body IS NOT NULL
      AND REGEXP_CONTAINS(
        LOWER(comment_body),
        r'\\b(chatgpt|copilot|gpt[- ]?4|gpt[- ]?3|gpt|claude|llm|generated by ai|generated with ai)\\b'
      )
    ORDER BY created_at DESC
    LIMIT @limit_comments
    """


def extract_matched_keyword(text: str) -> Optional[str]:
    if not text:
        return None
    match = AI_REGEX.search(text)
    return match.group(1).lower() if match else None


def query_candidate_comments(
    client: bigquery.Client,
    start_date: str,
    end_date: str,
    limit_comments: int,
) -> List[CandidateComment]:
    query = build_bq_query()
    job_config = bigquery.QueryJobConfig(
        query_parameters=[
            bigquery.ScalarQueryParameter("start_date", "DATE", start_date),
            bigquery.ScalarQueryParameter("end_date", "DATE", end_date),
            bigquery.ScalarQueryParameter("limit_comments", "INT64", limit_comments),
        ]
    )
    df = client.query(query, job_config=job_config).to_dataframe()
    records: List[CandidateComment] = []
    for row in df.to_dict(orient="records"):
        body = row.get("comment_body") or ""
        records.append(
            CandidateComment(
                repo_name=row["repo_name"],
                pr_number=int(row["pr_number"]),
                comment_id=row.get("comment_id"),
                actor_login=row.get("actor_login"),
                created_at=row["created_at"],
                comment_body=body,
                matched_keyword=extract_matched_keyword(body),
            )
        )
    return records


class GitHubAPI:
    def __init__(self, token: str, sleep: float = 0.2) -> None:
        self.session = requests.Session()
        self.session.headers.update(
            {
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
            }
        )
        self.sleep = sleep

    def _get(self, url: str, params: Optional[Dict[str, Any]] = None) -> Any:
        resp = self.session.get(url, params=params, timeout=60)
        if resp.status_code == 403:
            raise RuntimeError(
                f"GitHub API rate-limited or forbidden: {resp.status_code} {resp.text[:200]}"
            )
        resp.raise_for_status()
        time.sleep(self.sleep)
        return resp.json()

    def get_repo(self, owner: str, repo: str) -> Dict[str, Any]:
        return self._get(f"https://api.github.com/repos/{owner}/{repo}")

    def get_pr(self, owner: str, repo: str, pr_number: int) -> Dict[str, Any]:
        return self._get(f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}")

    def list_issue_comments(self, owner: str, repo: str, issue_number: int) -> List[Dict[str, Any]]:
        return self._paginate(
            f"https://api.github.com/repos/{owner}/{repo}/issues/{issue_number}/comments"
        )

    def list_reviews(self, owner: str, repo: str, pr_number: int) -> List[Dict[str, Any]]:
        return self._paginate(f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}/reviews")

    def list_review_comments(self, owner: str, repo: str, pr_number: int) -> List[Dict[str, Any]]:
        return self._paginate(
            f"https://api.github.com/repos/{owner}/{repo}/pulls/{pr_number}/comments"
        )

    def _paginate(self, url: str) -> List[Dict[str, Any]]:
        page = 1
        results: List[Dict[str, Any]] = []
        while True:
            data = self._get(url, params={"per_page": 100, "page": page})
            if not data:
                break
            results.extend(data)
            if len(data) < 100:
                break
            page += 1
        return results


def split_repo_name(repo_name: str) -> Tuple[str, str]:
    parts = repo_name.split("/", 1)
    if len(parts) != 2:
        raise ValueError(f"Invalid repo name: {repo_name}")
    return parts[0], parts[1]


def contains_ai_reference(text: Optional[str]) -> bool:
    return bool(text and AI_REGEX.search(text))


def safe_parse_dt(value: Optional[str]) -> Optional[pd.Timestamp]:
    if not value:
        return None
    try:
        return pd.Timestamp(dtparser.parse(value))
    except Exception:
        return None


def enrich_prs(
    github: GitHubAPI,
    candidate_comments: List[CandidateComment],
    max_prs: int,
    min_stars: int,
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    grouped: Dict[Tuple[str, int], List[CandidateComment]] = collections.defaultdict(list)
    for comment in candidate_comments:
        grouped[(comment.repo_name, comment.pr_number)].append(comment)

    selected_items = list(grouped.items())[:max_prs]

    pr_rows: List[Dict[str, Any]] = []
    issue_comment_rows: List[Dict[str, Any]] = []
    review_rows: List[Dict[str, Any]] = []

    for (repo_name, pr_number), candidate_group in tqdm(selected_items, desc="Enriching PRs"):
        owner, repo = split_repo_name(repo_name)

        try:
            repo_meta = github.get_repo(owner, repo)
            if int(repo_meta.get("stargazers_count", 0)) < min_stars:
                continue

            pr = github.get_pr(owner, repo, pr_number)
            issue_comments = github.list_issue_comments(owner, repo, pr_number)
            reviews = github.list_reviews(owner, repo, pr_number)
            review_comments = github.list_review_comments(owner, repo, pr_number)
        except Exception as exc:
            print(f"[WARN] Failed {repo_name}#{pr_number}: {exc}", file=sys.stderr)
            continue

        candidate_texts = [item.comment_body for item in candidate_group]
        candidate_keywords = [item.matched_keyword for item in candidate_group if item.matched_keyword]

        pr_rows.append(
            {
                "repo_name": repo_name,
                "owner": owner,
                "repo": repo,
                "repo_stars": repo_meta.get("stargazers_count"),
                "repo_language": repo_meta.get("language"),
                "pr_number": pr_number,
                "pr_id": pr.get("id"),
                "pr_state": pr.get("state"),
                "pr_title": pr.get("title"),
                "pr_user": (pr.get("user") or {}).get("login"),
                "created_at": pr.get("created_at"),
                "updated_at": pr.get("updated_at"),
                "closed_at": pr.get("closed_at"),
                "merged_at": pr.get("merged_at"),
                "merged": pr.get("merged"),
                "draft": pr.get("draft"),
                "commits": pr.get("commits"),
                "additions": pr.get("additions"),
                "deletions": pr.get("deletions"),
                "changed_files": pr.get("changed_files"),
                "requested_reviewers_count": len(pr.get("requested_reviewers") or []),
                "issue_comments_count_api": len(issue_comments),
                "reviews_count_api": len(reviews),
                "review_comments_count_api": len(review_comments),
                "candidate_ai_comment_count_bq": len(candidate_group),
                "candidate_ai_keywords_bq": json.dumps(sorted(set(candidate_keywords))),
                "candidate_ai_comment_examples_bq": json.dumps(candidate_texts[:3], ensure_ascii=False),
            }
        )

        for comment in issue_comments:
            body = comment.get("body") or ""
            issue_comment_rows.append(
                {
                    "repo_name": repo_name,
                    "pr_number": pr_number,
                    "comment_type": "issue_comment",
                    "comment_id": comment.get("id"),
                    "user_login": (comment.get("user") or {}).get("login"),
                    "created_at": comment.get("created_at"),
                    "body": body,
                    "contains_ai_reference": contains_ai_reference(body),
                }
            )

        for review_comment in review_comments:
            body = review_comment.get("body") or ""
            issue_comment_rows.append(
                {
                    "repo_name": repo_name,
                    "pr_number": pr_number,
                    "comment_type": "review_comment",
                    "comment_id": review_comment.get("id"),
                    "user_login": (review_comment.get("user") or {}).get("login"),
                    "created_at": review_comment.get("created_at"),
                    "body": body,
                    "contains_ai_reference": contains_ai_reference(body),
                }
            )

        for review in reviews:
            body = review.get("body") or ""
            review_rows.append(
                {
                    "repo_name": repo_name,
                    "pr_number": pr_number,
                    "review_id": review.get("id"),
                    "user_login": (review.get("user") or {}).get("login"),
                    "submitted_at": review.get("submitted_at"),
                    "state": review.get("state"),
                    "body": body,
                    "contains_ai_reference": contains_ai_reference(body),
                }
            )

    return (
        pd.DataFrame(pr_rows),
        pd.DataFrame(issue_comment_rows),
        pd.DataFrame(review_rows),
    )


def add_derived_columns(
    pr_df: pd.DataFrame,
    comments_df: pd.DataFrame,
    reviews_df: pd.DataFrame,
) -> pd.DataFrame:
    if pr_df.empty:
        return pr_df

    pr_df = pr_df.copy()

    pr_df["created_at_dt"] = pd.to_datetime(pr_df["created_at"], errors="coerce", utc=True)
    pr_df["closed_at_dt"] = pd.to_datetime(pr_df["closed_at"], errors="coerce", utc=True)
    pr_df["merged_at_dt"] = pd.to_datetime(pr_df["merged_at"], errors="coerce", utc=True)

    pr_df["time_to_close_hours"] = (
        (pr_df["closed_at_dt"] - pr_df["created_at_dt"]).dt.total_seconds() / 3600.0
    )
    pr_df["time_to_merge_hours"] = (
        (pr_df["merged_at_dt"] - pr_df["created_at_dt"]).dt.total_seconds() / 3600.0
    )

    if not comments_df.empty:
        ai_comment_counts = (
            comments_df.groupby(["repo_name", "pr_number"])["contains_ai_reference"]
            .sum()
            .reset_index(name="ai_reference_comment_count_all_comments")
        )
        total_comment_counts = (
            comments_df.groupby(["repo_name", "pr_number"])
            .size()
            .reset_index(name="total_comment_count_all_comments")
        )
        pr_df = pr_df.merge(ai_comment_counts, on=["repo_name", "pr_number"], how="left")
        pr_df = pr_df.merge(total_comment_counts, on=["repo_name", "pr_number"], how="left")
    else:
        pr_df["ai_reference_comment_count_all_comments"] = 0
        pr_df["total_comment_count_all_comments"] = 0

    if not reviews_df.empty:
        review_state_counts = (
            reviews_df.pivot_table(
                index=["repo_name", "pr_number"],
                columns="state",
                values="review_id",
                aggfunc="count",
                fill_value=0,
            )
            .reset_index()
        )
        review_state_counts.columns = [
            str(column).lower() if isinstance(column, str) else column
            for column in review_state_counts.columns
        ]
        pr_df = pr_df.merge(review_state_counts, on=["repo_name", "pr_number"], how="left")
    return pr_df.fillna(0)


def compute_stats(
    pr_df: pd.DataFrame,
    comments_df: pd.DataFrame,
    reviews_df: pd.DataFrame,
) -> Dict[str, Any]:
    stats: Dict[str, Any] = {}

    stats["n_prs"] = int(len(pr_df))
    stats["n_repos"] = int(pr_df["repo_name"].nunique()) if not pr_df.empty else 0
    stats["n_comments"] = int(len(comments_df))
    stats["n_reviews"] = int(len(reviews_df))

    if not pr_df.empty:
        stats["merged_rate"] = float(pd.to_numeric(pr_df["merged"], errors="coerce").fillna(0).mean())
        stats["median_time_to_merge_hours"] = (
            float(pd.to_numeric(pr_df["time_to_merge_hours"], errors="coerce").dropna().median())
            if pr_df["time_to_merge_hours"].notna().any()
            else None
        )
        stats["median_total_comments_per_pr"] = float(
            pd.to_numeric(pr_df["total_comment_count_all_comments"], errors="coerce").fillna(0).median()
        )
        stats["median_ai_reference_comments_per_pr"] = float(
            pd.to_numeric(pr_df["ai_reference_comment_count_all_comments"], errors="coerce").fillna(0).median()
        )
        stats["top_repos_by_pr_count"] = pr_df["repo_name"].value_counts().head(20).to_dict()
        stats["top_languages"] = pr_df["repo_language"].fillna("Unknown").value_counts().head(20).to_dict()

    if not comments_df.empty:
        keyword_counter = collections.Counter()
        for text in comments_df.loc[comments_df["contains_ai_reference"] == True, "body"].dropna():
            for match in AI_REGEX.findall(text):
                keyword_counter[match.lower()] += 1
        stats["ai_keyword_counts_in_comments"] = dict(keyword_counter.most_common(20))

    if not reviews_df.empty:
        stats["review_state_counts"] = reviews_df["state"].fillna("UNKNOWN").value_counts().to_dict()

    return stats


def save_outputs(
    output_dir: Path,
    candidate_comments: List[CandidateComment],
    pr_df: pd.DataFrame,
    comments_df: pd.DataFrame,
    reviews_df: pd.DataFrame,
    stats: Dict[str, Any],
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)

    candidate_df = pd.DataFrame([asdict(item) for item in candidate_comments])

    candidate_df.to_csv(output_dir / "candidate_ai_comments_from_bq.csv", index=False)
    pr_df.to_csv(output_dir / "pull_requests.csv", index=False)
    comments_df.to_csv(output_dir / "comments.csv", index=False)
    reviews_df.to_csv(output_dir / "reviews.csv", index=False)

    with open(output_dir / "summary_stats.json", "w", encoding="utf-8") as file_obj:
        json.dump(stats, file_obj, ensure_ascii=False, indent=2)

    lines = [
        "# Summary",
        f"- PRs: {stats.get('n_prs', 0)}",
        f"- Repos: {stats.get('n_repos', 0)}",
        f"- Comments: {stats.get('n_comments', 0)}",
        f"- Reviews: {stats.get('n_reviews', 0)}",
        f"- Merged rate: {stats.get('merged_rate')}",
        f"- Median time to merge (hours): {stats.get('median_time_to_merge_hours')}",
        "",
        "## Top repos by PR count",
    ]
    for key, value in (stats.get("top_repos_by_pr_count") or {}).items():
        lines.append(f"- {key}: {value}")
    lines.append("")
    lines.append("## AI keyword counts in comments")
    for key, value in (stats.get("ai_keyword_counts_in_comments") or {}).items():
        lines.append(f"- {key}: {value}")

    with open(output_dir / "summary_report.md", "w", encoding="utf-8") as file_obj:
        file_obj.write("\n".join(lines))


def main() -> None:
    args = parse_args()
    github_token, gcp_project = ensure_env()

    output_dir = Path(args.output_dir)

    print("[1/4] Querying candidate AI-reference PR comments from BigQuery...")
    bq_client = get_bigquery_client(gcp_project)
    candidate_comments = query_candidate_comments(
        client=bq_client,
        start_date=args.start,
        end_date=args.end,
        limit_comments=args.limit_comments,
    )
    print(f"Found {len(candidate_comments)} candidate AI-reference comments from GH Archive.")

    print("[2/4] Enriching PRs with GitHub API...")
    github = GitHubAPI(token=github_token, sleep=args.sleep)
    pr_df, comments_df, reviews_df = enrich_prs(
        github=github,
        candidate_comments=candidate_comments,
        max_prs=args.max_prs,
        min_stars=args.min_stars,
    )

    print("[3/4] Deriving metrics...")
    pr_df = add_derived_columns(pr_df, comments_df, reviews_df)
    stats = compute_stats(pr_df, comments_df, reviews_df)

    print("[4/4] Saving outputs...")
    save_outputs(output_dir, candidate_comments, pr_df, comments_df, reviews_df, stats)

    print("\nDone.")
    print(json.dumps(stats, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
